name: VTK compilation

on:
  push:
    branches: [ master ]
    tags: '**'
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/kmturbulenz/llvm-osmesa-image:sha-3e6fde5

    steps:
    - uses: actions/checkout@v3

    - name: Wheel cache
      id: wheel-cache
      uses: actions/cache@v3
      with:
        path: |
          vtk-*.whl
          *.log
        key: build-${{ github.sha }}

    - name: Compile VTK
      if: steps.wheel-cache.outputs.cache-hit != 'true'
      run: |
        ./build.sh

    - uses: actions/upload-artifact@v3
      with:
        name: VTK-wheel
        path: |
          vtk-*.whl
          *.log

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_type == 'tag'}}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: VTK-wheel

    - name: Create and upload release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          vtk-*.whl
